#!/usr/bin/env python3
import subprocess
import sys

def main():
    engine_path = "./src/stockfish"
    proc = subprocess.Popen(
        [engine_path],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1
    )

    def write_line(line):
        proc.stdin.write(line + "\n")
        proc.stdin.flush()

    def read_until_ready():
        while True:
            line = proc.stdout.readline().strip()
            if line == "readyok":
                break

    write_line("uci")
    while True:
        line = proc.stdout.readline().strip()
        if line == "uciok":
            break

    write_line("setoption name UCI_Variant value spell-chess")
    write_line("isready")
    read_until_ready()

    moves = []
    ply = 0
    max_plies = 40  # Play 20 full moves

    print("# Spell Chess Self-Play Transcript\n")
    print("This transcript is generated by running deterministic engine self-play on `spell-chess`.\n")

    while ply < max_plies:
        # Get board state and FEN by executing "d" command
        pos_cmd = "position startpos"
        if moves:
            pos_cmd += " moves " + " ".join(moves)
        write_line(pos_cmd)
        write_line("d")
        write_line("isready")
        read_until_ready()

        # Parse the output of "d"
        board_ascii = []
        fen = ""
        reading_board = False
        while True:
            line = proc.stdout.readline().strip()
            if line.startswith("Fen:"):
                fen = line.replace("Fen:", "").strip()
            elif line.startswith("+---") or line.startswith("+  +"):
                reading_board = True
                board_ascii.append(line)
            elif reading_board:
                board_ascii.append(line)
                if line.startswith("g h") or "a b c d e f g h" in line or line.startswith("Co"):
                    reading_board = False
            if "readyok" in line:
                break

        # Get best move from the engine
        write_line("go depth 6")  # Low depth for fast but reasonable moves
        bestmove = ""
        while True:
            line = proc.stdout.readline().strip()
            if line.startswith("bestmove"):
                parts = line.split()
                bestmove = parts[1]
                break

        player = "White" if ply % 2 == 0 else "Black"
        move_num = (ply // 2) + 1
        
        print(f"## Move {move_num}: {player} played `{bestmove}`")
        print(f"**FEN:** `{fen}`\n")
        print("```")
        for bline in board_ascii:
            print(bline)
        print("```\n")

        if bestmove == "(none)":
            print(f"Game over. {player} has no legal moves.")
            break

        moves.append(bestmove)
        ply += 1

    print("## Final Move List")
    print(" ".join(moves))

    proc.terminate()

if __name__ == "__main__":
    main()
